hand_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

hand_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - index_joint
    - middle_joint
    - ring_joint
    - pinky_joint
    - thumb1_joint
    - thumb2_joint

hand_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - index_joint
    - middle_joint
    - ring_joint
    - pinky_joint
    - thumb1_joint
    - thumb2_joint

hand_effort_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - index_joint
    - middle_joint
    - ring_joint
    - pinky_joint
    - thumb1_joint
    - thumb2_joint